Repository knative/release, pull requests merged in 2021-05, with the labels that each got.

#12 Add OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#13 some mods based on .23
  README.md
Labels: approved, cla: yes, lgtm, size/M

#11 Remove grantr from release lead list
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#16 Add `knative/client` and its plugins to the release process
  README.md
Labels: approved, cla: yes, lgtm, size/M

#17 Update client release instructions
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#18 Updates based on .23 release experience.
  README.md
Labels: approved, cla: yes, lgtm, size/S

#20 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#21 Remove myself following-up knative/community#628
  README.md
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS
