Repository knative/release, pull requests merged in 2021-12, with the labels that each got.

#70 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm

#67 Update README.md
  README.md
Labels: cla: yes, size/M, approved, lgtm

#71 Add net-gateway-api to release list
  README.md
Labels: cla: yes, approved, lgtm, size/XS

#72 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#74 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#75 Use correct versions for 1.* and later
  README.md
Labels: approved, lgtm, size/XS

#77 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
