Repository knative/release, pull requests merged in 2021-08, with the labels that each got.

#39 Correct the 0.29 release to January
  README.md
Labels: cla: yes, approved, lgtm, size/XS

#41 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm

#43 Remove Scott from Eventing Releases
  README.md
Labels: cla: yes, approved, kind/removal, lgtm, size/XS
