Repository knative/release, pull requests merged in 2022-06, with the labels that each got.

#133 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#134 drop eventing-natss from release
  INSTRUCTIONS.md
  README.md
Labels: approved, lgtm, size/XS

#135 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#136 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#138 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#139 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#132 Add checklists + restructure instructions
  .github/ISSUE_TEMPLATE/release-checklist.yaml
  INSTRUCTIONS.md
  PROCEDURES.md
  README.md
  ROSTER.md
  TIMELINE.md
  images/prow-search.png
Labels: approved, size/XL, lgtm

#143 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review
