Repository knative/release, pull requests merged in 2022-09, with the labels that each got.

#161 :broom: Quarterly release cadence
  README.md
  TIMELINE.md
Labels: size/S, approved, lgtm

#163 [feat] Adding kn-plugin-func label
  .github/ISSUE_TEMPLATE/release-checklist.yaml
Labels: approved, kind/enhancement, lgtm, size/XS

#162 [feat] Adding kn-plugin-func to release page
  TIMELINE.md
Labels: approved, kind/enhancement, lgtm, size/XS

#165 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
