Repository knative/release, pull requests merged in 2022-10, with the labels that each got.

#167 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#171 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#172 Bump knobots update-deps job at post release
  .github/ISSUE_TEMPLATE/release-checklist.yaml
Labels: approved, lgtm, size/XS

#174 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
