Repository knative/release, pull requests merged in 2022-01, with the labels that each got.

#78 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, approved, lgtm

#80 Remove some repos from the release train
  README.md
Labels: approved, lgtm, size/XS

#79 Use post v1.0 example for releasability update
  README.md
Labels: approved, lgtm, size/XS

#81 Remove test-infra from release
  README.md
Labels: approved, lgtm, size/XS

#76 :gift: Adding kn-plugin-event to the list of releases
  README.md
Labels: approved, kind/enhancement, lgtm, size/XS

#82 Add leads for v1.3 and v1.4
  README.md
Labels: approved, lgtm, size/XS

#85 Remove website repo from release train
  README.md
Labels: approved, lgtm, size/XS

#86 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
