Repository knative/release, pull requests merged in 2022-04, with the labels that each got.

#102 Extend release schedule through v1.9
  README.md
Labels: approved, lgtm, size/XS

#113 Update release instructions
  README.md
Labels: size/S, approved, lgtm

#114 update location of releasability version numbers
  README.md
Labels: approved, lgtm, size/XS

#116 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#117 Drop myself from the release roster
  README.md
Labels: approved, lgtm, size/XS

#120 Clean up list of releases to only future releases
  README.md
Labels: size/S, approved, lgtm

#121 releasing instructions updates
  README.md
  SCHEDULE.md
Labels: size/L, approved, kind/documentation, lgtm

#122 Volunteer gab-satchi for eventing release 1.5
  SCHEDULE.md
Labels: approved, lgtm, size/XS

#123 Remove client's special step
  README.md
Labels: approved, lgtm, size/XS

#124 minor updates to release instructions
  README.md
Labels: size/S, approved, kind/enhancement, lgtm

#125 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
