Repository knative/release, pull requests merged in 2022-05, with the labels that each got.

#126 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#127 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#128 Add link to dot release trigger documentation
  README.md
Labels: approved, lgtm, size/XS

#129 Add instructions on updating release schedule
  README.md
Labels: approved, lgtm, size/XS

#130 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#131 Refactor docs for easier reference
  INSTRUCTIONS.md
  README.md
  ROSTER.md
Labels: approved, size/XL, lgtm
