Repository knative/release, pull requests merged in 2023-07, with the labels that each got.

#224 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#228 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#226 Add eventing-istio to release
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-sandbox-eventing-istio.yaml
  TIMELINE.md
  repos.yaml
Labels: size/M, approved, lgtm

#230 Add eventing-istio to release-checklist
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#231 Add sample repos to eventing PR query
  PROCEDURES.md
Labels: approved, lgtm, size/XS

#232 Update releasability action to 1.11
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#233 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#234 Fix links in release check-list
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#235 Fix indentation in release-checklist.md
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#236 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
