Repository knative/release, pull requests merged in 2023-08, with the labels that each got.

#237 Add start-sha
  .github/workflows/release-note.yaml
Labels: approved, lgtm, size/XS

#238 Rename knative-sandbox to knative-extensions
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-sandbox-eventing-autoscaler-keda.yaml
  .github/workflows/knative-sandbox-eventing-ceph.yaml
  .github/workflows/knative-sandbox-eventing-github.yaml
  .github/workflows/knative-sandbox-eventing-gitlab.yaml
  .github/workflows/knative-sandbox-eventing-istio.yaml
  .github/workflows/knative-sandbox-eventing-kafka-broker.yaml
  .github/workflows/knative-sandbox-eventing-kafka.yaml
  .github/workflows/knative-sandbox-eventing-kogito.yaml
  .github/workflows/knative-sandbox-eventing-rabbitmq.yaml
  .github/workflows/knative-sandbox-eventing-redis.yaml
  .github/workflows/knative-sandbox-kn-plugin-admin.yaml
  .github/workflows/knative-sandbox-kn-plugin-event.yaml
  .github/workflows/knative-sandbox-kn-plugin-quickstart.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kafka.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kamelet.yaml
  .github/workflows/knative-sandbox-net-certmanager.yaml
  .github/workflows/knative-sandbox-net-contour.yaml
  .github/workflows/knative-sandbox-net-gateway-api.yaml
  .github/workflows/knative-sandbox-net-http01.yaml
  .github/workflows/knative-sandbox-net-istio.yaml
  .github/workflows/knative-sandbox-net-kourier.yaml
  .github/workflows/knative-sandbox-reconciler-test.yaml
  .github/workflows/knative-sandbox-sample-controller.yaml
  .github/workflows/knative-sandbox-sample-source.yaml
  .github/workflows/release-note.yaml
  PROCEDURES.md
  TIMELINE.md
  hack/update-timeline-refs.sh
  repos.yaml
Labels: approved, size/XL, lgtm

#239 Update schedule with upcoming releases
  README.md
Labels: approved, lgtm, size/XS

#240 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#241 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#242 File renames
  .github/workflows/knative-extensions-eventing-autoscaler-keda.yaml
  .github/workflows/knative-extensions-eventing-ceph.yaml
  .github/workflows/knative-extensions-eventing-github.yaml
  .github/workflows/knative-extensions-eventing-gitlab.yaml
  .github/workflows/knative-extensions-eventing-istio.yaml
  .github/workflows/knative-extensions-eventing-kafka-broker.yaml
  .github/workflows/knative-extensions-eventing-kafka.yaml
  .github/workflows/knative-extensions-eventing-kogito.yaml
  .github/workflows/knative-extensions-eventing-rabbitmq.yaml
  .github/workflows/knative-extensions-eventing-redis.yaml
  .github/workflows/knative-extensions-kn-plugin-admin.yaml
  .github/workflows/knative-extensions-kn-plugin-event.yaml
  .github/workflows/knative-extensions-kn-plugin-quickstart.yaml
  .github/workflows/knative-extensions-kn-plugin-source-kafka.yaml
  .github/workflows/knative-extensions-kn-plugin-source-kamelet.yaml
  .github/workflows/knative-extensions-net-certmanager.yaml
  .github/workflows/knative-extensions-net-contour.yaml
  .github/workflows/knative-extensions-net-gateway-api.yaml
  .github/workflows/knative-extensions-net-http01.yaml
  .github/workflows/knative-extensions-net-istio.yaml
  .github/workflows/knative-extensions-net-kourier.yaml
  .github/workflows/knative-extensions-reconciler-test.yaml
  .github/workflows/knative-extensions-sample-controller.yaml
  .github/workflows/knative-extensions-sample-source.yaml
Labels: approved, lgtm, size/XS

#243 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
