Repository knative/release, pull requests merged in 2023-01, with the labels that each got.

#181 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#183 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#182 remove nader-ziada from release roster
  ROSTER.md
Labels: approved, lgtm, size/XS
