Repository knative/release, pull requests merged in 2023-04, with the labels that each got.

#192 Centralize releasability checks
  .github/workflows/check-owners.yaml
  .github/workflows/knative-caching.yaml
  .github/workflows/knative-client-pkg.yaml
  .github/workflows/knative-client.yaml
  .github/workflows/knative-eventing.yaml
  .github/workflows/knative-func.yaml
  .github/workflows/knative-networking.yaml
  .github/workflows/knative-pkg.yaml
  .github/workflows/knative-sandbox-control-protocol.yaml
  .github/workflows/knative-sandbox-eventing-autoscaler-keda.yaml
  .github/workflows/knative-sandbox-eventing-ceph.yaml
  .github/workflows/knative-sandbox-eventing-github.yaml
  .github/workflows/knative-sandbox-eventing-gitlab.yaml
  .github/workflows/knative-sandbox-eventing-kafka-broker.yaml
  .github/workflows/knative-sandbox-eventing-kafka.yaml
  .github/workflows/knative-sandbox-eventing-kogito.yaml
  .github/workflows/knative-sandbox-eventing-rabbitmq.yaml
  .github/workflows/knative-sandbox-eventing-redis.yaml
  .github/workflows/knative-sandbox-kn-plugin-admin.yaml
  .github/workflows/knative-sandbox-kn-plugin-event.yaml
  .github/workflows/knative-sandbox-kn-plugin-quickstart.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kafka.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kamelet.yaml
  .github/workflows/knative-sandbox-net-certmanager.yaml
  .github/workflows/knative-sandbox-net-contour.yaml
  .github/workflows/knative-sandbox-net-gateway-api.yaml
  .github/workflows/knative-sandbox-net-http01.yaml
  .github/workflows/knative-sandbox-net-istio.yaml
  .github/workflows/knative-sandbox-net-kourier.yaml
  .github/workflows/knative-sandbox-reconciler-test.yaml
  .github/workflows/knative-sandbox-sample-controller.yaml
  .github/workflows/knative-sandbox-sample-source.yaml
  .github/workflows/knative-serving.yaml
  .github/workflows/releasability.yaml
  hack/update-workflows.sh
  repos.yaml
Labels: approved, size/XXL, lgtm

#194 update release leads for 1.10
  README.md
  ROSTER.md
Labels: approved, lgtm, size/XS

#195 Update release documentation
  .github/workflows/knative-operator.yaml
  PROCEDURES.md
  TIMELINE.md
  hack/update-timeline-refs.sh
  repos.yaml
Labels: size/L, approved, lgtm

#197 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#198 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#200 tweak some cron settings for workflows
  .github/workflows/check-owners.yaml
  .github/workflows/knative-caching.yaml
  .github/workflows/knative-client-pkg.yaml
  .github/workflows/knative-client.yaml
  .github/workflows/knative-eventing.yaml
  .github/workflows/knative-func.yaml
  .github/workflows/knative-networking.yaml
  .github/workflows/knative-operator.yaml
  .github/workflows/knative-pkg.yaml
  .github/workflows/knative-sandbox-control-protocol.yaml
  .github/workflows/knative-sandbox-eventing-autoscaler-keda.yaml
  .github/workflows/knative-sandbox-eventing-ceph.yaml
  .github/workflows/knative-sandbox-eventing-github.yaml
  .github/workflows/knative-sandbox-eventing-gitlab.yaml
  .github/workflows/knative-sandbox-eventing-kafka-broker.yaml
  .github/workflows/knative-sandbox-eventing-kafka.yaml
  .github/workflows/knative-sandbox-eventing-kogito.yaml
  .github/workflows/knative-sandbox-eventing-rabbitmq.yaml
  .github/workflows/knative-sandbox-eventing-redis.yaml
  .github/workflows/knative-sandbox-kn-plugin-admin.yaml
  .github/workflows/knative-sandbox-kn-plugin-event.yaml
  .github/workflows/knative-sandbox-kn-plugin-quickstart.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kafka.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kamelet.yaml
  .github/workflows/knative-sandbox-net-certmanager.yaml
  .github/workflows/knative-sandbox-net-contour.yaml
  .github/workflows/knative-sandbox-net-gateway-api.yaml
  .github/workflows/knative-sandbox-net-http01.yaml
  .github/workflows/knative-sandbox-net-istio.yaml
  .github/workflows/knative-sandbox-net-kourier.yaml
  .github/workflows/knative-sandbox-reconciler-test.yaml
  .github/workflows/knative-sandbox-sample-controller.yaml
  .github/workflows/knative-sandbox-sample-source.yaml
  .github/workflows/knative-serving.yaml
  hack/update-workflows.sh
Labels: size/L, approved, lgtm

#201 fix check owner files workflow
  .github/workflows/check-owners.yaml
Labels: approved, lgtm, size/XS

#199 Centralize Release Notes Workflow
  .github/workflows/release-note.yaml
Labels: size/L, approved, lgtm

#202 Update release check list
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/release-checklist.yaml
Labels: approved, size/XL, lgtm

#203 Fix codeowners workflow
  .github/workflows/check-owners.yaml
Labels: approved, lgtm, size/XS

#205 Correct release-checklist.md
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: size/L, approved, lgtm

#209 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#206 Remove optional step at knative/client repo
  .github/ISSUE_TEMPLATE/release-checklist.md
  PROCEDURES.md
Labels: approved, lgtm, size/XS
