Repository knative/release, pull requests merged in 2023-10, with the labels that each got.

#248 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#249 Update release leads for 1.12
  README.md
  ROSTER.md
Labels: approved, lgtm, size/XS

#250 Update releasability action to 1.12
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#251 Revert "Update releasability action to 1.12 (#250)"
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#255 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#256 Drop control-protocol repository as it is archived
  PROCEDURES.md
Labels: approved, lgtm, size/XS

#254 update slack channel names
  PROCEDURES.md
  TIMELINE.md
Labels: approved, lgtm, size/XS

#259 Move EKB repo to phase 4 in release-checklist template
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: size/S, approved, lgtm
