Repository knative/release, pull requests merged in 2023-05, with the labels that each got.

#211 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#212 [releasability] only print result to slack if we triggered the job manually
  .github/workflows/knative-caching.yaml
  .github/workflows/knative-client-pkg.yaml
  .github/workflows/knative-client.yaml
  .github/workflows/knative-eventing.yaml
  .github/workflows/knative-func.yaml
  .github/workflows/knative-networking.yaml
  .github/workflows/knative-operator.yaml
  .github/workflows/knative-pkg.yaml
  .github/workflows/knative-sandbox-control-protocol.yaml
  .github/workflows/knative-sandbox-eventing-autoscaler-keda.yaml
  .github/workflows/knative-sandbox-eventing-ceph.yaml
  .github/workflows/knative-sandbox-eventing-github.yaml
  .github/workflows/knative-sandbox-eventing-gitlab.yaml
  .github/workflows/knative-sandbox-eventing-kafka-broker.yaml
  .github/workflows/knative-sandbox-eventing-kafka.yaml
  .github/workflows/knative-sandbox-eventing-kogito.yaml
  .github/workflows/knative-sandbox-eventing-rabbitmq.yaml
  .github/workflows/knative-sandbox-eventing-redis.yaml
  .github/workflows/knative-sandbox-kn-plugin-admin.yaml
  .github/workflows/knative-sandbox-kn-plugin-event.yaml
  .github/workflows/knative-sandbox-kn-plugin-quickstart.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kafka.yaml
  .github/workflows/knative-sandbox-kn-plugin-source-kamelet.yaml
  .github/workflows/knative-sandbox-net-certmanager.yaml
  .github/workflows/knative-sandbox-net-contour.yaml
  .github/workflows/knative-sandbox-net-gateway-api.yaml
  .github/workflows/knative-sandbox-net-http01.yaml
  .github/workflows/knative-sandbox-net-istio.yaml
  .github/workflows/knative-sandbox-net-kourier.yaml
  .github/workflows/knative-sandbox-reconciler-test.yaml
  .github/workflows/knative-sandbox-sample-controller.yaml
  .github/workflows/knative-sandbox-sample-source.yaml
  .github/workflows/knative-serving.yaml
  .github/workflows/releasability.yaml
  hack/update-workflows.sh
Labels: size/M, approved, lgtm

#210 add skonto to release roster & sign him up for v1.11 release
  README.md
  ROSTER.md
Labels: size/S, approved, lgtm

#213 Added Vishal-Chdhry to v1.11 release for eventing
  README.md
Labels: size/S, approved, lgtm

#214 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review
