Repository knative/release, pull requests merged in 2023-06, with the labels that each got.

#216 Add Operator badge
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#217 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#218 Remove archived knative-sandbox/control-protocol repository
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-sandbox-control-protocol.yaml
  TIMELINE.md
  repos.yaml
Labels: size/M, approved, lgtm

#219 Migrate timeline info to checklist and procedure
  .github/ISSUE_TEMPLATE/release-checklist.md
  PROCEDURES.md
  hack/update-timeline-refs.sh
Labels: size/L, approved, lgtm

#220 Remove gab-satchi from release roster
  ROSTER.md
Labels: approved, lgtm, size/XS

#221 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#222 Add checklist item to improve release process
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#223 Add query for open eventing PRs from bots
  PROCEDURES.md
Labels: size/S, approved, lgtm
