Repository knative/release, pull requests merged in 2024-07, with the labels that each got.

#315 Add release leads rotation for Knative v1.15
  README.md
Labels: approved, lgtm, size/XS

#317 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#318 Update releasability default to 1.15
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#319 :lady_beetle: Use Go1.22 for releaseability checks
  .github/workflows/releasability.yaml
Labels: kind/bug, approved, lgtm, size/XS

#320 Add new release notes generator to procedure docs
  PROCEDURES.md
Labels: approved, lgtm, size/XS

#321 Switch to shared Go setup
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#322 Update steps to publish homebrew-client
  PROCEDURES.md
Labels: size/S, approved, lgtm

#323 Add autoscaler keda
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-extensions-autoscaler-keda.yaml
  repos.yaml
Labels: size/M, approved, lgtm
