Repository knative/release, pull requests merged in 2024-04, with the labels that each got.

#295 add leads for v1.14 release
  README.md
Labels: approved, lgtm, size/XS

#297 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#296 Revert "drop eventing-rabbitmq from release train"
  .github/ISSUE_TEMPLATE/release-checklist.md
  PROCEDURES.md
  TIMELINE.md
  repos.yaml
Labels: size/M, approved, lgtm

#298 Update releasability default to 1.14
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#299 Adding eventing-natss again
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-extensions-eventing-natss.yaml
  repos.yaml
Labels: size/M, approved, lgtm

#300 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#301 Remove eventing-kafka from release
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-extensions-eventing-kafka.yaml
  repos.yaml
Labels: size/M, approved, lgtm

#302 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#304 Remove archived knative-extensions/net-certmanager repository
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-extensions-net-certmanager.yaml
  TIMELINE.md
  repos.yaml
Labels: size/M, approved, lgtm
