Repository knative/release, pull requests merged in 2025-04, with the labels that each got.

#348 Fixes after 1.17
  .github/ISSUE_TEMPLATE/release-checklist.md
  PROCEDURES.md
Labels: size/S, approved, lgtm

#354 Update releasability to next version 1.18
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#355 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#356 fix: Remove slack link from TIMELINE template
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#357 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#358 Add Knative v1.21 release schedule
  README.md
Labels: approved, lgtm, size/XS
