Repository knative/release, pull requests merged in 2025-07, with the labels that each got.

#359 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#365 Remove client-pkg from release checklist
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: size/S, approved, lgtm

#366 Remove kamelet plugin from release steps
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/knative-extensions-kn-plugin-source-kamelet.yaml
  TIMELINE.md
  repos.yaml
Labels: size/M, approved, lgtm
