Repository knative/release, pull requests merged in 2025-01, with the labels that each got.

#341 Update release leads for Knative 1.17
  README.md
Labels: size/S, approved, lgtm

#342 Update releasability default to 1.17
  .github/workflows/releasability.yaml
Labels: approved, lgtm, size/XS

#343 include updating operator supported versions in release checklist
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: approved, lgtm, size/XS

#344 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#345 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#346 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#347 Update release schedule for next cycle
  README.md
Labels: approved, lgtm, size/XS
